server:
  port: 8081
spring:
  application:
    name: "loan-microservice"
  devtools:
    add-properties: false
  flyway:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    org.flywaydb: INFO
    co.com.cristiancabarcas: DEBUG

adapters:
  r2dbc:
    host: ${DATABASE_HOST:localhost}
    port: ${DATABASE_PORT:3306}
    database: ${DATABASE_NAME:pragma}
    username: ${DATABASE_USERNAME:pragma}
    password: ${DATABASE_PASSWORD:pragma}

security:
  jwt:
    secret: ${JWT_SECRET:pragma}